name: underground_railroad
description: A secure, anonymous messaging and alert system built on Veilid with nation-state-level security and plausible deniability
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.6.2

  # Data Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Encrypted Storage
  sqflite_sqlcipher: ^3.1.1
  flutter_secure_storage: ^9.2.2

  # Security
  biometric_storage: ^5.0.1
  local_auth: ^2.3.0
  cryptography: ^2.7.0
  crypto: ^3.0.6

  # Veilid Integration
  flutter_rust_bridge: ^2.11.0
  ffi: ^2.1.3

  # Utilities
  path_provider: ^2.1.5
  path: ^1.9.0
  uuid: ^4.5.1
  intl: ^0.20.1

  # Logging
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
