name: underground_railroad
description: Secure assistance coordination network for people fleeing persecution (native platforms only)
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Native platforms only - web intentionally excluded for security
# See NATIVE_ONLY.md for rationale

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # FFI to Rust core
  ffi: ^2.1.0

  # Veilid for mobile anonymous networking
  veilid:
    path: ../../veilid/veilid-flutter

  # QR codes
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.0

  # Secure storage
  flutter_secure_storage: ^9.0.0

  # Biometric auth
  local_auth: ^2.1.0

  # State management
  provider: ^6.1.0

  # Navigation
  go_router: ^12.0.0

  # File system
  path_provider: ^2.1.0

  # Permissions
  permission_handler: ^11.0.0
  flutter_rust_bridge: 2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
